### ISSUE TITLE
Travis CI for macOS always failed

### ISSUE THREAD

**Issue by nekketsuuu** [gfngfn/SATySFi#24]
I don't know why, but Travis CI jobs for macOS seems to be always errored, whereas jobs for Linux are passed. For example, look at [this build](https://travis-ci.org/gfngfn/SATySFi/builds/340178759).

The output says the compilation of `ppx_derivers`, `cppo` and `result` failed.
How about running `cat` stdout-file to know the reason of the errors?

**Comment by objmagic** [comment]
Same with my PR. After checking travis CI config for some other popular packages (like `ppx_deriving`), it seems people do not test on osx

**Comment by nekketsuuu** [comment]
@gfngfn I think this should not be closed yet because #16 has not been merged. (See comments on #27)

**Comment by gfngfn** [comment]
Oops, I misunderstood the comment… (I haven’t merged #16 yet because I had failed to install the package `camlimages` 4.2.5 for OCaml 4.06 via OPAM on macOS 10.12 due to a kind of bug in `camlimages` 4.2.5; see [the issue I reported](https://bitbucket.org/camlspotter/camlimages/issues/22/cannot-install-camlimages-425-via-opam-for) for detail)
